ALTER TABLE media ADD COLUMN IF NOT EXISTS playback_status TEXT NOT NULL DEFAULT 'ready';
ALTER TABLE media ADD COLUMN IF NOT EXISTS prepared_path TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS prepare_progress DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN IF NOT EXISTS prepare_error TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS force_transcode BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE media ADD COLUMN IF NOT EXISTS season_number INT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS episode_number INT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS release_year INT;
